package testcases;

import org.testng.Assert;
import org.testng.annotations.Test;

public class LoginTest {
	
	@Test
	public void doLogin(){
		String expectedResult ="A";
		String actualResult ="A";
		
		Assert.assertEquals(actualResult, expectedResult);
		
		Assert.assertTrue(5>2,"User Given Error Message"); // (condition,ErrorMessgae)
		
		Assert.fail("Custom Error -  Error 404");
		
		// If run fails on any of assertion the run will break in between , to avoid it use soft assertion to continue flow of the program.
		
	}

}
